### ISSUE TITLE
error date

### ISSUE THREAD

**Issue by hala54** [sage-org/sage-client#11]
PREFIX  dc:   <http://purl.org/dc/elements/1.1/>
PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dbpedia2: <http://dbpedia.org/property/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  dbo:  <http://dbpedia.org/ontology/>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  dbpedia: <http://dbpedia.org/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>

SELECT  ?name ?birth ?person
WHERE
  { ?person dbpedia2:birthPlace :France .
    ?person dbo:birthDate ?birth .
    ?person foaf:name ?name
FILTER ( ?birth < "1970-01-01"^^xsd:date )
  }
ORDER BY ?name

Error: Unknown Datatype found during RDF Term parsing: 1970-01-01 (datatype: http://www.w3.org/2001/XMLSchema#date)

**Comment by Callidon** [comment]
This is a known bug, from the `sparql-engine` framework. It will be fixed in the next version.

**Comment by Callidon** [comment]
Fixed with ec0d7a4128197d282ad1e99ac3441f4474a90f1f
