### ISSUE TITLE
reqte on SWDF 2012 does not display results

### ISSUE THREAD

**Issue by hala54** [sage-org/sage-client#12]
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX owl: <http://www.w3.org/2002/07/owl#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
SELECT DISTINCT ?name ?l 
WHERE { <http://data.semanticweb.org/person/jan-carlson> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:Person 
{ <http://data.semanticweb.org/person/jan-carlson> foaf:name ?name } 
UNION { <http://data.semanticweb.org/person/jan-carlson> rdfs:label ?l } 
}

**Comment by Callidon** [comment]
fixed in lastest release
