### ISSUE TITLE
Unsupported keyword: (NOT) EXISTS

### ISSUE THREAD

**Issue by Rintarou** [sage-org/sage-client#5]
When running any query from the
exist/ or negation/ folder
of the [w3c SPARQL 1.1 compliance benchmark](https://www.w3.org/TR/sparql11-query/)

There is no current support for the `exist` and `not exist` keywords.

**Comment by Callidon** [comment]
Implementing (NOT) EXISTS requires a new physical operator. One possible implementation is to run subqueries in parallels to test existence. Need to investigate that in detail...

**Comment by Callidon** [comment]
Added in [`sparql-engine@0.2.1`](https://github.com/Callidon/sparql-engine/releases/tag/v0.2.1)
