### ISSUE TITLE
Unsupported keyword: MINUS

### ISSUE THREAD

**Issue by Rintarou** [sage-org/sage-client#6]
When running any query from the
negation/ folder
of the [w3c SPARQL 1.1 compliance benchmark](https://www.w3.org/TR/sparql11-query/)

There is no current support for the `minus` keyword.

**Comment by Callidon** [comment]
Implementing MINUS required a new physical query operator which implements the DIFFERENCE operator from relational algebra.

**Comment by Callidon** [comment]
Added in [`sparql-engine@0.2.1`](https://github.com/Callidon/sparql-engine/releases/tag/v0.2.1)
