### ISSUE TITLE
The query doesn't stop after 500 bindings with JS client

### ISSUE THREAD

**Issue by momo54** [sage-org/sage-client#9]
The query doesn't stop after 500 bindings with JS client

prefix dbo: http://dbpedia.org/ontology/
prefix dbr: http://dbpedia.org/resource/
prefix rdfs: http://www.w3.org/2000/01/rdf-schema#

SELECT DISTINCT ?performer ?name WHERE {
?work dbo:writer ?y;
dbo:musicalArtist ?performer.
OPTIONAL {
?performer rdfs:label ?name.
FILTER LANGMATCHES(LANG(?name), "EN")
}
} limit 500

**Comment by Callidon** [comment]
Fixed in 4bdff2b1757f3c82208e44f35b276ef37114d310
The pre-fetch fo Sage pags was not interrupted after the LIMIT was reached.
Fixed using the `finalize` operator in **rxjs** to perform some cleanup.
